### ISSUE TITLE
Error running the command 

### ISSUE THREAD

**Issue by saikrishna321** [isonic1/flick#7] opened 2016-09-17 05:45 UTC
flick video -a start -p android

/usr/local/lib/ruby/gems/2.3.0/gems/flick-0.2.3/lib/flick/system.rb:7:in `mkdir': No such file or directory @ dir_s_mkdir - /Users/saikrisv/.flick/192.168.68.101:5555 (Errno::ENOENT)
       	from /usr/local/lib/ruby/gems/2.3.0/gems/flick-0.2.3/lib/flick/system.rb:7:in `setup_system_dir'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/flick-0.2.3/lib/flick/android.rb:23:in `create_flick_dirs'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/flick-0.2.3/lib/flick/android.rb:15:in `initialize'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/flick-0.2.3/lib/flick/video.rb:15:in `new'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/flick-0.2.3/lib/flick/video.rb:15:in `initialize'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/flick-0.2.3/bin/flick:32:in `new'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/flick-0.2.3/bin/flick:32:in `block (2 levels) in <top (required)>'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:68:in `run!'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/import.rb:5:in `block in <top (required)>'

**Comment by isonic1** [comment] 2016-09-17 14:53
Hmm, I've pulled that version of the gem. Can you do a "gem install flick" and try again? You should get version 3.0 now. Thank you for reporting the problem.

**Comment by isonic1** [comment] 2016-09-20 16:53
@saikrishna321 did 0.3.0 fix this problem? I'm unable to reproduce the issue now.

**Comment by saikrishna321** [comment] 2016-09-21 04:53
@isonic1 i still the have issue with v 3.0.0

```
flick video -a start -p android -u 32085b6d8fdb71ff --trace
/usr/local/lib/ruby/gems/2.3.0/gems/flick-0.3.0/lib/flick/system.rb:7:in `mkdir': No such file or directory @ dir_s_mkdir - /Users/saikrisv/.flick/32085b6d8fdb71ff (Errno::ENOENT)
       	from /usr/local/lib/ruby/gems/2.3.0/gems/flick-0.3.0/lib/flick/system.rb:7:in `setup_system_dir'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/flick-0.3.0/lib/flick/android.rb:27:in `create_flick_dirs'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/flick-0.3.0/lib/flick/android.rb:19:in `initialize'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/flick-0.3.0/lib/flick/video.rb:15:in `new'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/flick-0.3.0/lib/flick/video.rb:15:in `initialize'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/flick-0.3.0/bin/flick:32:in `new'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/flick-0.3.0/bin/flick:32:in `block (2 levels) in <top (required)>'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:68:in `run!'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/import.rb:5:in `block in <top (required)>'
```

**Comment by isonic1** [comment] 2016-09-21 20:47
Doh! I see the problem. Sorry about that. I'll fix it soon. Thank you @saikrishna321 for letting me know.

**Comment by saikrishna321** [comment] 2016-09-22 00:03
@isonic1 most welcome :) waiting for the fix. I basically want to use this plugin in my parallel appium framework. Please take a look 

https://github.com/saikrishna321/AppiumTestDistribution

**Comment by isonic1** [comment] 2016-09-22 00:31
@saikrishna321 it's fixed now. I just pushed 0.3.1 and yanked 0.3.0. Please do a "gem update flick" to get the latest. I'm pretty sure it will work now. Thanks again! :) 

Your Appium Test Distribution looks awesome! I'll definitely pass it on as reference for others wanting to do the same in java!

**Comment by saikrishna321** [comment] 2016-09-22 07:08
@isonic1 it started the recording, but stopping the recording i see MP4BOX stop unexpectedly,
```
~ ᐅ flick video -a start -p android -u 32085b6d8fdb71ff --trace
zsh: correct 'android' to '.android' [nyae]? n
Starting Recorder In Normal Mode.
Recorder will automatically stop after 180 seconds...
~ ᐅ flick video -a stop -p android -u 32085b6d8fdb71ff --trace
zsh: correct 'android' to '.android' [nyae]? n

Stopping Recorder!!!
[iso file] Incomplete box mdat
[iso file] Incomplete MDAT while file is not read-only
No suitable media tracks to cat in /Users/saikrisv/.flick/32085b6d8fdb71ff/video-single.mp4 - skipping
Saving to /Users/saikrisv/32085b6d8fdb71ff.mp4
/usr/local/lib/ruby/gems/2.3.0/gems/flick-0.3.1/lib/flick/video.rb:107:in `rename': No such file or directory @ rb_file_s_rename - (/Users/saikrisv/.flick/32085b6d8fdb71ff/32085b6d8fdb71ff.mp4, /Users/saikrisv/32085b6d8fdb71ff.mp4) (Errno::ENOENT)
       	from /usr/local/lib/ruby/gems/2.3.0/gems/flick-0.3.1/lib/flick/video.rb:107:in `stop_record'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/flick-0.3.1/lib/flick/video.rb:49:in `stop'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/flick-0.3.1/lib/flick/video.rb:25:in `run'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/flick-0.3.1/bin/flick:32:in `block (2 levels) in <top (required)>'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:68:in `run!'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/import.rb:5:in `block in <top (required)>'
```

**Comment by isonic1** [comment] 2016-09-22 17:01
@saikrishna321 hmm, that seems like a mp4box error. Did you install using homebrew? I would uninstall it and reinstall. Maybe also update brew if you didn't do that already.

**Comment by saikrishna321** [comment] 2016-09-22 17:19
@isonic1 yah i did install it by brew .. will give it a try again .. Is there any other medium i can chat on this? gitter , skype, slack or gtalk ?

**Comment by saikrishna321** [comment] 2016-09-22 17:42
@isonic1 got it working :) thanks a lot 👍 how can i extend the time from 180 seconds ?

**Comment by isonic1** [comment] 2016-09-22 18:05
sweet! Yeah, you can extend it by passing -e true in the start action. e.g. flick video -p android -a start -e true . Thank you again for reporting this. Proves how helpful tests can be, which I need to update them. :)

**Closed** 2016-09-22 19:17 UTC
Labels: bug

**Comment by saikrishna321** [comment] 2016-09-23 04:10
@isonic1 thanks for building flick 👍  very helpful
